# Generated by Django 5.0.4 on 2025-01-18 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
