# Generated by Django 5.0.4 on 2025-01-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('street',models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('zip_code', models.TextField()),
                ('country', models.TextField())
            ],
        ),
        # TODO: implement Update Model for the address field in Profiles
    ]
