# Generated by Django 5.0.4 on 2025-01-18 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_customuser_dccuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField()),
                ('phone_number', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('about_me', models.TextField()),
                ('leetcode_username', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='dccuser',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
            preserve_default=False,
        ),
    ]
