# Generated by Django 5.0.4 on 2025-01-20 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_dccpermission_dccpermissions_dccgroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DCCPermissions',
        ),
    ]
