# Generated by Django 5.0.4 on 2025-01-20 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_dccpermissions'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='dccgroup',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dccpermission',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dccgroup',
            name='group_permissions',
            field=models.ManyToManyField(blank=True, help_text='The permissions this group has.', related_name='customuser_set', to='accounts.dccpermission', verbose_name='permissions'),
        ),
        migrations.AlterField(
            model_name='dccuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='customusergroup_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='dccuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customuserpermission_set', to='accounts.dccpermission', verbose_name='user permissions'),
        ),
    ]
