# Generated by Django 5.0.4 on 2025-01-20 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_dccgroup_description_dccpermission_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dccgroup',
            options={'verbose_name': 'group', 'verbose_name_plural': 'groups'},
        ),
        migrations.AlterField(
            model_name='dccgroup',
            name='group_permissions',
            field=models.ManyToManyField(blank=True, help_text='The permissions this group has.', related_name='dccgroup_set', to='accounts.dccpermission', verbose_name='permissions'),
        ),
        migrations.AlterField(
            model_name='dccuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='dccuser_set', to='accounts.dccgroup', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='dccuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='dccuser_set', to='accounts.dccpermission', verbose_name='user permissions'),
        ),
    ]
